### PR TITLE
Update Publish Yaml

### PR DESCRIPTION
**Pull request by cmgrier**
Trying another solution to fix the publish script

### CODE REVIEW

**Comment by kenyee** [comment]
weird...why do UI tests fail w/ that change? 🤔 

And you should always use ./gradlew because that locks down the gradle version...if you gradle directly, it depends on what the version installed on the system is...

**Comment by ghost** [comment]
> weird...why do UI tests fail w/ that change? 🤔
> 
> And you should always use ./gradlew because that locks down the gradle version...if you gradle directly, it depends on what the version installed on the system is...

Hey @kenyee.  👋 
Great callouts!

There's an issue with Github actions where they timeout a lot when downloading external dependencies.  From a lot of research that i did, there are issues with the Azure servers that are causing the issue.  One fix that I added to the actions was to use gradle caching and that helps with sequential builds with the same action.  The UI tests sometimes fail to run due to this issue.

I agree, that would be the optimal thing to do: using ./gradlew.  There's a bug that's occurring with the publish action where it cannot locate ./gradlew. Others have reported success with using gradle, which @cmgrier is trying out.

**Comment by kenyee** [comment]
> There's a bug that's occurring with the publish action where it cannot locate ./gradlew

That would be bizarre...would be worth doing an ls -l to see if it's in the right place w/ the right perms...

**Comment by ghost** [comment]
> > There's a bug that's occurring with the publish action where it cannot locate ./gradlew
> 
> That would be bizarre...would be worth doing an ls -l to see if it's in the right place w/ the right perms...

That's a good idea.

**Comment by kenyee** [comment]
you should really take jcenter out of your list of repos....

**Comment by kenyee** [comment]
hmm..interesting...it's not in the list of repos...but the failure log has it hitting jcenter 🤔

**Comment by kenyee** [comment]
also why does it use Kotlin 1.5.31?  That's ancient...

**Comment by kenyee** [comment]
the last repo in the list looks like a dup:
```
        google()
        gradlePluginPortal()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
```
AFAIK, that's the same as "gradlePluginPortal"...

**Review by ghost — APPROVED** [review]

**Pull request merged**
